### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by johnshift** [johnshift/veils#163]
## Description
Users should be able to comment on posts or other comments.

**Subtasks:**
- [ ] Comment on post
- [ ] Comment on comment
- [ ] Toggle comment tree
- [ ] Delete comment
