### ISSUE TITLE
Profile/Veil

### ISSUE THREAD

**Issue by johnshift** [johnshift/veils#166]
## Description
Each user should have a profile page and a veil page

**Subtasks:**
- [ ] User profile page.
- [ ] User veil page.
- [ ] Upload profile/veil picture.
- [ ] Edit description.
